# 회원가입 API

POST http://localhost:3000/api/auth/sign-up
Content-Type: application/json

{
  "userId":"test23",
  "password":"1234",
  "passwordCheck":"1234",
  "name":"song",
  "phone":"1122",
  "email":"test23@mail.com",
  "birthday": "1930-12-30"
}

###

# 로그인
POST http://localhost:3000/api/auth/log-in
Content-Type: application/json

{
  "userId": "song4",
  "password": "1234"
}

###

# 캐시 테스트용 getUsers
GET http://localhost:3000/api/auth/test-auth
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEwIiwiaWF0IjoxNjc4MDI1NTgxLCJleHAiOjE2NzgwMjkxODF9.8zdT2JpdqLWZ-lWlS07Ztjz9IxZhXUPNEvWxx4lIDcA; Path=/,refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NzgwMjU1ODEsImV4cCI6MTY3ODEwODM4MX0.nfVsigVfDskea4DxIqXHzlvZImYIMyyLZEmJ5qGiLbo; Path=/


