name: glamping-CICD-test

on:
  push:
    branches: forTest

jobs:
  AUTO_DEPLOY:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run scripts in server
        uses: appleboy/ssh-action@master
        env:
          TEST_SONG: ${{ secrets.TEST_SONG }}
          
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSH_KEY }}
          envs: 
            TEST_SONG
            
          script: |            
            # TEST
            export TEST_SONG=$TEST_SONG
            
            cd 5jo
            git branch
            pm2 stop main
            npm run build
            pm2 start dist/main.js
            
