name: IF-EVENT

on:
  pull_request:
    branches: forTest-main
  push:
    branches: forTest-main
  merge:
    branches: forTest-main

jobs:
  AUTO_DEPLOY:
    runs-on: ubuntu-latest

    steps:
      - name: if_push
        if: github.event.push
        run: |
          echo PUSH!

      - name: if_pr
        if: github.event.pull_request
        run: |
          echo PULL_REQUEST!

        # - name: Run scripts in server
        #   uses: appleboy/ssh-action@master
        #   env:
        #     TEST_SONG: ${{ secrets.TEST_SSONG }}
        #     TEST_SONG2: ${{ secrets.TEST_SSONG2 }}
        #     DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
        #     DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
        #     DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
        #     DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
        #     DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
        #     ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
        #     HASH_SALT_OR_ROUND: ${{ secrets.HASH_SALT_OR_ROUND }}
        #     JWT_SECRET: ${{ secrets.JWT_SECRET }}
        #     REFRESHTOKEN_HOST: ${{ secrets.REFRESHTOKEN_HOST }}
        #     REFRESHTOKEN_PORT: ${{ secrets.REFRESHTOKEN_PORT }}
        #     REFRESHTOKEN_EXP: ${{ secrets.REFRESHTOKEN_EXP }}
        #     REFRESHTOKEN_PASSWORD: ${{ secrets.REFRESHTOKEN_PASSWORD }}
        #     BASIC_ORIGIN: ${{ secrets.BASIC_ORIGIN }}
        #     BASIC_CDN: ${{ secrets.BASIC_CDN }}
        #     SOCKET_NAMESPACE_CHAT: ${{ secrets.SOCKET_NAMESPACE_CHAT }}
        #     SOCKET_NAMESPACE_RESERVE: ${{ secrets.SOCKET_NAMESPACE_RESERVE }}
        #     GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
        #     GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
        #     GOOGLE_CALLBACK_URL: ${{ secrets.GOOGLE_CALLBACK_URL }}
        #     TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
        #     TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}

        #   with:
        #     host: ${{ secrets.HOST }}
        #     username: ${{ secrets.USERNAME }}
        #     password: ${{ secrets.PASSWORD }}
        #     port: ${{ secrets.PORT }}
        #     key: ${{ secrets.SSH_KEY }}
        #     envs: DATABASE_PORT,
        #       DATABASE_HOST,
        #       DATABASE_NAME,
        #       DATABASE_USERNAME,
        #       DATABASE_PASSWORD,
        #       ADMIN_PASSWORD,
        #       HASH_SALT_OR_ROUND,
        #       JWT_SECRET,
        #       REFRESHTOKEN_HOST,
        #       REFRESHTOKEN_PORT,
        #       REFRESHTOKEN_EXP,
        #       REFRESHTOKEN_PASSWORD,
        #       BASIC_ORIGIN,
        #       BASIC_CDN,
        #       SOCKET_NAMESPACE_CHAT,
        #       SOCKET_NAMESPACE_RESERVE,
        #       GOOGLE_CLIENT_ID,
        #       GOOGLE_CLIENT_SECRET,
        #       GOOGLE_CALLBACK_URL,
        #       TWILIO_ACCOUNT_SID,
        #       TWILIO_AUTH_TOKEN

        #     script: |
        #       # DB 정보
        #       export DATABASE_PORT=$DATABASE_PORT
        #       export DATABASE_HOST=$DATABASE_HOST
        #       export DATABASE_NAME=$DATABASE_NAME
        #       export DATABASE_USERNAME=$DATABASE_USERNAME
        #       export DATABASE_PASSWORD=$DATABASE_PASSWORD

        #       # 관리자 정보
        #       export ADMIN_PASSWORD=$ADMIN_PASSWORD

        #       # JWT 정보
        #       export HASH_SALT_OR_ROUND=$HASH_SALT_OR_ROUND
        #       export JWT_SECRET=$JWT_SECRET

        #       # REDIS 정보
        #       export REFRESHTOKEN_HOST=$REFRESHTOKEN_HOST
        #       export REFRESHTOKEN_PORT=$REFRESHTOKEN_PORT
        #       export REFRESHTOKEN_EXP=$REFRESHTOKEN_EXP
        #       export REFRESHTOKEN_PASSWORD=$REFRESHTOKEN_PASSWORD

        #       # DOMAIN 정보
        #       export BASIC_ORIGIN=$BASIC_ORIGIN
        #       export BASIC_CDN=$BASIC_CDN

        #       # SOCKET 정보
        #       export SOCKET_NAMESPACE_CHAT=$SOCKET_NAMESPACE_CHAT
        #       export SOCKET_NAMESPACE_RESERVE=$SOCKET_NAMESPACE_RESERVE

        #       # 소셜 로그인 정보
        #       export GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
        #       export GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET
        #       export GOOGLE_CALLBACK_URL=$GOOGLE_CALLBACK_URL

        #       # Twilio 정보
        #       export TWILIO_ACCOUNT_SID=$TWILIO_ACCOUNT_SID
        #       export TWILIO_AUTH_TOKEN=$TWILIO_AUTH_TOKEN

        #       cd 5jo
        #       npm run build --if-present
        #       npm run test
