name: glamping-CICD

on:
  push:
    branches: dev
  pull_request:
    branches: dev

jobs:
  AUTO_DEPLOY:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Run scripts in server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd 5jo
            git pull origin dev
            npm run deploy
  
